### ISSUE TITLE
[Proposal] Dynamically adding more content to the page

### ISSUE THREAD

**Issue by ScSherifTarek** [rinvex/laravel-pages#13]
Taking into consideration pages with more content like faq page that needs more than only a title, subtitle, excerpt, and content it will be nice if we can extend the data that could be changed dynamically to more maybe we can call the column `data`.

This column can contain a JSON string that represents all the data needed for the current page for example in a faq it will contain an array of the questions with their answers. so when these data are passed to the view the developer will be responsible for rendering it.

Another implementation  -which I think is more complex but introduces more usability- could be using a Schema for defining what data the view needs and based on it each page uses this view should provide the data needed for its schema. introducing a predefined schema will make it easier to render the data and will allow us easily generate a form for the admin to provide the data needed for each page.

this implementation will introduce the use of one view in multiple pages so I think the schema will look similar to this.

views table:
- id
- slug
- view_path
- schema

pages table:
- id
- slug
- view_id
- data
- other columns

**Comment by Omranic** [comment]
Thank you @ScSherifTarek for your proposal, any PRs are welcome 🙂
