### ISSUE TITLE
Published migrations are ignored

### ISSUE THREAD

**Issue by inmanturbo** [rinvex/laravel-pages#23]
calling `php artisan migrate:refresh --seed` after you've change a column or two (in this case I have changed sort_order to sort, because that's what I have in the config for spatie/eloquent-sortable) throws an error:

<pre><font color="#C4A000">Seeding:</font> Database\Seeders\PageSeeder

  <span style="background-color:#CC0000"><b> Illuminate\Database\QueryException </b></span>

<b>  SQLSTATE[42S22]: Column not found: 1054 Unknown column &apos;sort&apos; in &apos;field list&apos; (SQL: select max(`sort`) as aggregate from `pages` where `pages`.`deleted_at` is null)</b>

  at <font color="#4E9A06">vendor/laravel/framework/src/Illuminate/Database/Connection.php</font>:<font color="#4E9A06">692</font>
    <font color="#555753">688▕ </font><font color="#AD7FA8"><b>        </b></font><font color="#555753"><i>// If an exception occurs when attempting to run a query, we&apos;ll format the error</i></font>
    <font color="#555753">689▕ </font><font color="#555753"><i>        // message to include the bindings with SQL, which will make this exception a</i></font>
    <font color="#555753">690▕ </font><font color="#555753"><i>        // lot more helpful to the developer instead of just the database&apos;s errors.</i></font>
    <font color="#555753">691▕ </font><font color="#555753"><i>        </i></font><font color="#AD7FA8"><b>catch (</b></font><b>Exception $e</b><font color="#AD7FA8"><b>) {</b></font>
<font color="#EF2929"><b>  ➜ </b></font><i><b>692</b></i><font color="#555753">▕ </font><font color="#AD7FA8"><b>            throw new </b></font><b>QueryException</b><font color="#AD7FA8"><b>(</b></font>
    <font color="#555753">693▕ </font><font color="#AD7FA8"><b>                </b></font><b>$query</b><font color="#AD7FA8"><b>, </b></font><b>$this</b><font color="#AD7FA8"><b>-&gt;</b></font><b>prepareBindings</b><font color="#AD7FA8"><b>(</b></font><b>$bindings</b><font color="#AD7FA8"><b>), </b></font><b>$e</b>
    <font color="#555753">694▕ </font><b>            </b><font color="#AD7FA8"><b>);</b></font>
    <font color="#555753">695▕ </font><font color="#AD7FA8"><b>        }</b></font>
    <font color="#555753">696▕ </font>

  <font color="#729FCF"><b>• </b></font><b>A column was not found</b>: You might have forgotten to run your migrations. You can run your migrations using `php artisan migrate`. 
    <font color="#3465A4">https://laravel.com/docs/master/migrations#running-migrations</font>

      +27 vendor frames 
  <font color="#C4A000">28  </font><b>database/seeders/PageSeeder.php</b>:<b>18</b>
  <font color="#D3D7CF">    Illuminate\Database\Eloquent\Model::__callStatic()</font>

      +7 vendor frames 
  <font color="#C4A000">36  </font><b>database/seeders/DatabaseSeeder.php</b>:<b>24</b>
  <font color="#D3D7CF">    Illuminate\Database\Seeder::call()</font>
<font color="#EF2929"><b>➜  </b></font><font color="#34E2E2"><b>megaplate</b></font> <font color="#729FCF"><b>git:(</b></font><font color="#EF2929"><b>main</b></font><font color="#729FCF"><b>) </b></font><font color="#FCE94F"><b>✗</b></font> <font color="#4E9A06">php</font> <u style="text-decoration-style:single">artisan</u> db                    

MariaDB [megaplate]&gt; describe pages;
+------------+-----------------------+------+-----+---------+----------------+
| Field      | Type                  | Null | Key | Default | Extra          |
+------------+-----------------------+------+-----+---------+----------------+
| id         | int(10) unsigned      | NO   | PRI | NULL    | auto_increment |
| uri        | varchar(255)          | NO   |     | NULL    |                |
| slug       | varchar(255)          | NO   |     | NULL    |                |
| route      | varchar(255)          | NO   |     | NULL    |                |
| domain     | varchar(255)          | YES  | MUL | NULL    |                |
| middleware | longtext              | YES  |     | NULL    |                |
| title      | longtext              | NO   |     | NULL    |                |
| subtitle   | longtext              | YES  |     | NULL    |                |
| excerpt    | longtext              | YES  |     | NULL    |                |
| content    | longtext              | YES  |     | NULL    |                |
| view       | varchar(255)          | NO   |     | NULL    |                |
| is_active  | tinyint(1)            | NO   |     | 1       |                |
| sort_order | mediumint(8) unsigned | NO   |     | 0       |                |
| created_at | timestamp             | YES  |     | NULL    |                |
| updated_at | timestamp             | YES  |     | NULL    |                |
| deleted_at | timestamp             | YES  |     | NULL    |                |
+------------+-----------------------+------+-----+---------+----------------+
<b>16 rows in set (0.001 sec)</b>

MariaDB [megaplate]&gt; quit;
<b>Bye</b>
<font color="#8AE234"><b>➜  </b></font><font color="#34E2E2"><b>megaplate</b></font> <font color="#729FCF"><b>git:(</b></font><font color="#EF2929"><b>main</b></font><font color="#729FCF"><b>) </b></font><font color="#FCE94F"><b>✗</b></font> <font color="#4E9A06">cat</font> <u style="text-decoration-style:single">database/migrations/rinvex/laravel-pages/2021_06_30_193226_create_pages_table.php</u> 
&lt;?php

declare(strict_types=1);

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePagesTable extends Migration
{

    /**
     * The database schema.
     *
     * @var \Illuminate\Database\Schema\Builder
     */
    protected $schema;

    /**
     * Create a new migration instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this-&gt;schema = Schema::connection($this-&gt;getConnection());
    }

    /**
     * Get the migration connection name.
     *
     * @return string|null
     */
    public function getConnection()
    {
        return config(&apos;database.default&apos;);
    }

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up(): void
    {
        $this-&gt;schema-&gt;create(config(&apos;rinvex.pages.tables.pages&apos;), function (Blueprint $table) {
            // Columns
            $table-&gt;increments(&apos;id&apos;);
            $table-&gt;uuid(&apos;uuid&apos;);
            $table-&gt;string(&apos;uri&apos;);
            $table-&gt;string(&apos;slug&apos;);
            $table-&gt;string(&apos;route&apos;);
            $table-&gt;string(&apos;domain&apos;)-&gt;nullable();
            $table-&gt;text(&apos;middleware&apos;)-&gt;nullable();
            $table-&gt;text(&apos;title&apos;);
            $table-&gt;text(&apos;subtitle&apos;)-&gt;nullable();
            $table-&gt;text(&apos;excerpt&apos;)-&gt;nullable();
            $table-&gt;text(&apos;content&apos;)-&gt;nullable();
            $table-&gt;text(&apos;body&apos;);
            $table-&gt;string(&apos;layout&apos;)-&gt;nullable();
            $table-&gt;string(&apos;view&apos;);
            $table-&gt;boolean(&apos;is_active&apos;)-&gt;default(true);
            $table-&gt;mediumInteger(&apos;sort&apos;)-&gt;unsigned();
            $table-&gt;text(&apos;meta&apos;)-&gt;nullable();
            $table-&gt;unsignedBigInteger(&apos;created_by&apos;)-&gt;nullable();
            $table-&gt;unsignedBigInteger(&apos;updated_by&apos;)-&gt;nullable();
            $table-&gt;unsignedBigInteger(&apos;deleted_by&apos;)-&gt;nullable();
            $table-&gt;timestamps();
            $table-&gt;softDeletes();

            // Indexes
            $table-&gt;unique([&apos;domain&apos;, &apos;uri&apos;]);
            $table-&gt;unique([&apos;domain&apos;, &apos;slug&apos;]);
            $table-&gt;unique([&apos;domain&apos;, &apos;route&apos;]);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down(): void
    {
        $this-&gt;schema-&gt;dropIfExists(config(&apos;rinvex.pages.tables.pages&apos;));
    }
}
<font color="#8AE234"><b>➜  </b></font><font color="#34E2E2"><b>megaplate</b></font> <font color="#729FCF"><b>git:(</b></font><font color="#EF2929"><b>main</b></font><font color="#729FCF"><b>) </b></font><font color="#FCE94F"><b>✗</b></font> <font color="#4E9A06">cat</font> <u style="text-decoration-style:single">config/rinvex.pages.php</u>                                                          
&lt;?php

declare(strict_types=1);

return [

    // Manage autoload migrations
    &apos;autoload_migrations&apos; =&gt; true,

    // Pageable Database Tables
    &apos;tables&apos; =&gt; [
        &apos;pages&apos; =&gt; &apos;pages&apos;,
        &apos;pageables&apos; =&gt; &apos;pageables&apos;,
    ],

    // Pageable Models
    &apos;models&apos; =&gt; [
        &apos;page&apos; =&gt; \Rinvex\Pages\Models\Page::class,
    ],

    // Register routes
    &apos;register_routes&apos; =&gt; true,

];
<font color="#8AE234"><b>➜  </b></font><font color="#34E2E2"><b>megaplate</b></font> <font color="#729FCF"><b>git:(</b></font><font color="#EF2929"><b>main</b></font><font color="#729FCF"><b>) </b></font><font color="#FCE94F"><b>✗</b></font> 
</pre>

**Comment by inmanturbo** [comment]
I guess the solution is to move the migrations out of the sub-directory and set `rinvex.pages.autoload_migrations` to `false`.

**Comment by Omranic** [comment]
Exactly as you mentioned, the solution is to set `rinvex.pages.autoload_migrations` to `false` in your package's config options.
