### ISSUE TITLE
 Integrity constraint violation on pages.middleware

### ISSUE THREAD

**Issue by stephenr85** [rinvex/laravel-pages#28]
It looks like the middleware column is defined as json, but I don't see why in the code, and I'm not able to set it. Is there a reason for that?

**Comment by stephenr85** [comment]
I tried to workaround this by changing the page class used in the rinvex.pages config to my local \App\Models\Page class (which extends the Rinvex Page class), then adding a cast property for middleware => array, but that didn't work, as it's still pulled as a string in the route autoregistration.

I also tried to create a mutator, but the validation fails.
```
public function middleware() : Attribute
    {
        return Attribute::make(
            get: function($value) {
                return json_decode($value);
            },
            set: function($value) {
                return json_encode($value);
            }
        );
    }
```

I also wrote a migration to change the column to a string, but then I can only specify one middleware (piped syntax doesn't seem to work in v9?). I could create a separate middleware group for this, but meh...I'm getting into breaking forward-compatibility. The specifying middleware feature just seems to be broken.

**Comment by Omranic** [comment]
Hey @stephenr85, sorry for the late reply. The middleware field in the Laravel Eloquent model is a JSON type for flexibility and scalability. This allows each page to specify its own set of middleware dynamically, accommodating various requirements without altering the database schema. Using JSON simplifies the database structure, enables easy manipulation of middleware arrays, and integrates seamlessly with Laravel's routing system. This approach ensures that middleware configurations can be managed efficiently and adjusted as the application grows. Hope this helps.
